### ISSUE TITLE
Add support for REPL / interactive mode

### ISSUE THREAD

**Issue by koistya** [projectkudu/KuduExec#5]
For example:

```cmd
D:\home\site> node.exe -i
> console.log('hello')
```

or

```cmd
D:\home\site> sqlite3.exe db.sqlite
> SELECT * FROM Table;
```

**Comment by davidebbo** [comment]
Note that KuduExec is not being actively developed. Instead, we use the browser based Kudu console. And that doe work with 'node -i', though some other interactive scenarios may not work. Is still not a full on console, but it's a lot closer than KuduExec.

**Comment by koistya** [comment]
Ah, I see, thanks for the explanation.
